title: Artemis
domain: eeg.engin.umich.edu
url: https://eeg.engin.umich.edu
baseurl: /ArtemisUsers/

theme: just-the-docs

color_scheme: "light"
search_enabled: true

ga_tracking: G-X2LPWRLJ7X

includes:
  head:
    - head_custom.html

plugins:
  - jekyll-relative-links
